version: "3.8"

services:
  postgresql:
    restart: always
    image: postgres
    container_name: letter
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mcpmwC8gGwVKr4Q9xCKZEzEgS
      - POSTGRES_DB=letter
    ports:
      - '5433:5432'
#
#  file_storage_service_app:
#    image: 'application:latest'
#    build:
#      context: .
#    container_name: file_storage_service_app
#    ports:
#      - 8086:8086