spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/pejt_letter
    username: postgres
    password: 1234
    hikari:
      maximum-pool-size: 3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
server:
  port: 8086
interceptor:
  kafka:
    bootstrap: "localhost:9092"
    topic: "url"

