spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/pejt_letter
    username: postgres
    password: mcpmwC8gGwVKr4Q9xCKZEzEgS
    hikari:
      maximum-pool-size: 3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8086
interceptor:
  bootstrap: "localhost:9092"
  topic: "url"

