spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true


