spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/pejt_letter
    username: postgres
    password: mcpmwC8gGwVKr4Q9xCKZEzEgS
    hikari:
      maximum-pool-size: 3
  kafka:
    bootstrap: "localhost:9092"
    topic: "url"
  jpa:
    show-sql: true
server:
  port: 8086

