spring:
  datasource:
    url: jdbc:postgresql://192.168.1.1:5432/pejt_letter
    username: postgres
    password: 1234
    hikari:
      maximum-pool-size: 3
server:
  port: 8086
interceptor:
  kafka:
    bootstrap: "192.168.1.1:9092"
    topic: "url"


