spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/letter
    username: postgres
    password: mcpmwC8gGwVKr4Q9xCKZEzEgS
  liquibase:
    change-log: classpath:db\changelog\db.changelog-master.yaml

